### PR TITLE
Update container repository datawire

### PR DESCRIPTION
**Pull request by peteroneilljr**
This PR contains a handful of things. 
- Manifest points to Datawire repository
- Added in Skaffold config files 
- Added a readme to show how to build the containers
- Updated main.go to be more resilient

### CODE REVIEW

**Review by mattmcclure-dw — CHANGES_REQUESTED** [review]
Can you please update the -no-mapping.yaml file as well? That's the one we use in the quick start.

**Comment by peteroneilljr** [comment]
> Can you please update the -no-mapping.yaml file as well? That's the one we use in the quick start.

I added a `no-mapping` manifest file. Let me know if it looks good now @mattmcclure-dw

**Comment by mattmcclure-dw** [comment]
I think something's up with the `dataprocessingservice` container.  If I follow the quick start using your YAML file on step 3.1, on 3.3 I get an orange pod when it should be green.

**Comment by mattmcclure-dw** [comment]
issues fixed in https://github.com/datawire/edgey-corp-go/pull/4

**Pull request closed without merging**
